### ISSUE TITLE
How to get the same result

### ISSUE THREAD

**Issue by justinli** [charlesangus/Labelmaker#1]
How to get the same result

[python -exec {
#ID:claystudiofx
frame_mode=nuke.thisNode().knob('frame_mode').value()
frameval=nuke.thisNode().knob('frame').value()
first=nuke.thisNode().knob('first').value()
last=nuke.thisNode().knob('last').value()
dur= last-first+1
if frameval '' :
if frame_mode == 'start at' :
msg=frame_mode+ ' '+frameval.spli t('.',1)[0]
first2=int(floa t(frameval))
last2=first2+du r-1
elif frame_mode =='offset' :
if frame_mode=='of fset' :
msg=frame_mode+ ' : '+str((int(fram eval.split('.', 1)[0])))
offset=-int(flo at(frameval))
else :
offset=0
first2=first+of fset
last2=last+offs et
else:
msg='expr = '+frameval
first2=first
last2=last
else :
msg=''
offset=0
first2=first+of fset
last2=last+offs et}
][value width] x [value height]
Range:[python first2]-[python last2]
Frame long:[ python dur]
[python msg]

**Comment by charlesangus** [comment]
I don't think that code pasted in quite correctly, but it looks like more fundamentally the question is about how to embed the results of a python routine in a TCL string knob. Let me look into it in the general case and get back to you.

**Comment by charlesangus** [comment]
If you re-paste this code in a code block with the correct indentation, that would be helpful actually.

Also, which node class is this intended to run on?

**Comment by charlesangus** [comment]
Here's a toy example which may help you - the basic idea is to put each line of your label into its own TCL string, and move your python code into an external module.

In this example, I've added an object to the JSON file for the node class "NodeClass", then I'm using `[python -exec {` to import a module and store the result, and then display it using `[python time]`.

For you example, you could do something like `Range: [python -exec {import mymodule; values = mymodule.get_values()}][python values['first2']]-[python values['last2']`. 

```
"NodeClass": [
    "tcl_string": "[value width] x [value height]",
    "tcl_string": "time: [python -exec {import datetime;time = datetime.datetime.now()][python time]"
]
```

Hopefully that's helpful, let me know if you need more assistance.
